platform:ios,'8.0'
target 'Take_the_find' do 
pod 'Masonry'
pod 'SDWebImage', '~> 3.8.1’
pod 'SVProgressHUD', '~> 2.0.3’
pod 'AFNetworking', '~> 3.1.0'
pod 'SDCycleScrollView','~> 1.64’
pod 'MJRefresh'
end
